apiVersion: apps/v1
kind: Deployment
metadata:
  name: npvet-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npvet-backend
  template:
    metadata:
      labels:
        app: npvet-backend
    spec:
      tolerations:
        - key: "cloud.google.com/gke-quick-remove"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          operator: "Exists"
          effect: "NoExecute"
      containers:
        - name: npvet-backend
          image: us-central1-docker.pkg.dev/mensal04/npvet-repo/npvet-backend-cloud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"port":8080}}'
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          readinessProbe:
            httpGet:
              path: /npvet-api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"