apiVersion: v1
kind: Service
metadata:
  name: npvet-backend-service
  namespace: npvet-dev
spec:
  selector:
    app: npvet-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
