apiVersion: apps/v1
kind: Deployment
metadata:
  name: npvet-frontend
  namespace: npvet-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: npvet-frontend
  template:
    metadata:
      labels:
        app: npvet-frontend
    spec:
      containers:
        - name: npvet-frontend
          image: ghcr.io/orbitechz/npvet-frontend-cloud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://npvet-backend-service.npvet-k8s.svc.cluster.local"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
