apiVersion: apps/v1
kind: Deployment
metadata:
  name: npvet-backend-deployment
  namespace: npvet-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: npvet-backend
  template:
    metadata:
      labels:
        app: npvet-backend
    spec:
      containers:
        - name: npvet-backend
          image: ghcr.io/orbitechz/npvet-backend-cloud:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"port":8080}}'
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          readinessProbe:
            httpGet:
              path: /npvet-api/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
