apiVersion: v1
kind: Service
metadata:
  name: npvet-backend-service
  namespace: npvet-k8s
spec:
  selector:
    app: npvet-backend
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
