- op: replace
  path: /metadata/annotations/networking.gke.io~1managed-certificates
  value: npvet-cert-staging
- op: replace
  path: /metadata/annotations/kubernetes.io~1ingress.global-static-ip-name
  value: npvet-ip-staging
- op: replace
  path: /spec/rules/0/host
  value: npvet-staging.moschen.dev