apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: npvet-staging

resources:
  - ../../base/apps/backend
  - ../../base/apps/frontend
  - ../../base/apps/database
  - ../../base/infra/ingress
  - ./tls/managed-cert.yaml

patchesStrategicMerge:
  - ingress-patch.yaml

configMapGenerator:
  - name: backend-config
    env: backend/backend.env
  - name: postgres-config
    env: database/database.env

secretGenerator:
  - name: backend-secrets
    files:
      - backend/backend.properties
  - name: postgres-secrets
    files:
      - database/database.properties

images:
  - name: ghcr.io/orbitechz/npvet-backend-cloud
    newTag: staging
  - name: ghcr.io/orbitechz/npvet-frontend-cloud
    newTag: staging
