apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: npvet-staging

resources:
  - ../../base/apps/backend
  - ../../base/apps/frontend
  - ../../base/apps/database
  - ../../base/infra/ingress

configMapGenerator:
  - name: backend-config
    env: backend-staging.properties
  - name: postgres-config
    env: postgres-staging.properties

secretGenerator:
  - name: backend-secrets
    files:
      - backend-staging.env
  - name: postgres-secrets
    files:
      - postgres-staging.env

images:
  - name: ghcr.io/orbitechz/npvet-backend-cloud
    newTag: staging
  - name: ghcr.io/orbitechz/npvet-frontend-cloud
    newTag: staging
