apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: npvet-prod

resources:
  - ../../base/apps/backend
  - ../../base/apps/frontend
  - ../../base/apps/database
  - ../../base/infra/ingress
  - ./tls/managed-cert.yaml

replicas:
  - name: npvet-frontend
    count: 2
  - name: npvet-backend-deployment
    count: 2

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: npvet-frontend-ingress
    patch: |-
      - op: replace
        path: /metadata/annotations/networking.gke.io~1managed-certificates
        value: npvet-cert-prod
      - op: replace
        path: /metadata/annotations/kubernetes.io~1ingress.global-static-ip-name
        value: npvet-ip-prod
      - op: replace
        path: /spec/rules/0/host
        value: npvet.moschen.dev
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: backend-config
    env: backend/backend.properties
  - name: postgres-config
    env: database/database.properties

secretGenerator:
  - name: backend-secrets
    envs:
      - backend/backend.env
  - name: postgres-secrets
    envs:
      - database/database.env

images:
  - name: us-central1-docker.pkg.dev/mensal04/npvet-repo/npvet-frontend-cloud
    newTag: latest
  - name: us-central1-docker.pkg.dev/mensal04/npvet-repo/npvet-backend-cloud
    newTag: latest
