apiVersion: apps/v1
kind: Deployment
metadata:
  name: npvet-frontend
  namespace: npvet-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: npvet-frontend
  template:
    metadata:
      labels:
        app: npvet-frontend
    spec:
      tolerations:
        - key: "cloud.google.com/gke-quick-remove"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          operator: "Exists"
          effect: "NoExecute"
      containers:
        - name: npvet-frontend
          image: ghcr.io/orbitechz/npvet-frontend-cloud:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://npvet-backend-service.npvet-prod.svc.cluster.local"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
