apiVersion: v1
kind: Service
metadata:
  name: npvet-frontend
  namespace: npvet-prod
spec:
  selector:
    app: npvet-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
